### ISSUE TITLE
User can see their avatar, name, handle (unique), message_count, star_count

### ISSUE THREAD

**Issue by boulderReactCodingNight** [boulderReactCodingNight/03-react-twitter#12]
Use user information from #23 - probably will be passed via state. To start, just display hard coded data.

**Comment by AOrnstein** [comment]
We got this

**Comment by jenniferwiner** [comment]
@AOrnstein What was the progress on this one in the last meetup?

**Comment by jenniferwiner** [comment]
This is done!
