### ISSUE TITLE
User can see message feed sorted by date descending

### ISSUE THREAD

**Issue by boulderReactCodingNight** [boulderReactCodingNight/03-react-twitter#16]

**Comment by jenniferwiner** [comment]
https://material-ui.com/layout/grid/

**Comment by jenniferwiner** [comment]
@churel Is there any code you were able to finish? Should I make this available to people in our next meetup on Thursday?

**Comment by cfunkles** [comment]
Can you please Assign Charlie and Chuck to this one?

**Comment by cfunkles** [comment]
@jenniferwiner

**Comment by jenniferwiner** [comment]
Got it! Thanks!

**Comment by jenniferwiner** [comment]
@cfunkles https://stackoverflow.com/questions/41374572/how-to-render-an-array-of-objects-in-react

**Comment by cfunkles** [comment]
@jenniferwiner  this one is done I didn't the name in, but I'll close it

**Comment by cfunkles** [comment]
@jenniferwiner nope can't close it

**Comment by jenniferwiner** [comment]
@cfunkles Sounds good - great work! Closing this.
