### ISSUE TITLE
Create sign up component

### ISSUE THREAD

**Issue by boulderReactCodingNight** [boulderReactCodingNight/03-react-twitter#22]
User Story: As a user, I want to be able to register for an account on React-Twitter!

Create a sign up component. 

See user migration for more detail.
- Required fields: name, handle, email, password
- Optional: avatar, bio, location, birthday

**validate fields where necessary**

**Comment by BadrChoubai** [comment]
Brad and I will be working on this!

**Comment by BadrChoubai** [comment]
We completed the form and the api call but we were not able to handle anything after the user registered
