### ISSUE TITLE
Create tests for user methods

### ISSUE THREAD

**Issue by jenniferwiner** [boulderReactCodingNight/03-react-twitter#27]
Tests needed for login controller and signup controller

**Comment by DylanKojiCheslin** [comment]
working on this

**Comment by jenniferwiner** [comment]
@DylanKojiCheslin How's this one going?

**Comment by DylanKojiCheslin** [comment]
done except for two code paths. the path of validating base64 in the avatar error handling and the path of hashed password error handling. will merge what is done.
