### ISSUE TITLE
consolidate migrate/seeding of database to a yarn script

### ISSUE THREAD

**Issue by garyspencer** [boulderReactCodingNight/03-react-twitter#42]
It would be nice to have an installation of postgres as well as database seeding and migration from npm scripts.

for example:
 `yarn run seed` 

```bash
$ createdb react_twitter_dev
$ createdb react_twitter_test
$ cd server
$ knex migrate:latest
$ knex migrate:latest --env test
$ knex seed:run
$ knex seed:run --env test
$ cd ../
```

> Make sure you have postgres installed globally, then

Installing postgres automagically may be a challenge if we wanted to stay cross platform... could use `brew`, and apt or yum where available.  Windows would be left out in the cold.  Is that such a big deal though? 😝

**Comment by garyspencer** [comment]
WIP!

**Comment by garyspencer** [comment]
@jenniferwiner I have a pull request in, but may have overstepped w/ adding a dev dependency and possibly screwed up by including yarn.lock

**Comment by jenniferwiner** [comment]
Sounds great! Feel free to add dependencies as needed.
