### ISSUE TITLE
Users can create messages (aka tweet)

### ISSUE THREAD

**Issue by jenniferwiner** [boulderReactCodingNight/03-react-twitter#47]
Create a message component for users to create a message.
Use POST /messages to save message

**Comment by edsztukowski** [comment]
Working on this!

**Comment by carpenter-js** [comment]
We got this one

**Comment by carpenter-js** [comment]
Did this get resolved? I finished the POST on the front end for sending messages to the server, but it sounded like someone else beat me to it and made a pull request. If not let me know i'm happy to make a PR with my solution.

**Comment by jenniferwiner** [comment]
@carpenter-js Hey! I was looking for this comment. I remembered getting an email about it and couldn't find it. Yes looks like this was resolved - sorry about the assignee confusion. Hope to see you at the meetup on Thursday!
