### ISSUE TITLE
Create footer

### ISSUE THREAD

**Issue by jenniferwiner** [boulderReactCodingNight/03-react-twitter#50]
Footer should be visible on all pages
Can include:
- Link to the github page (https://github.com/boulderReactCodingNight/03-react-twitter/)
- Any info about our meetup
- Contact info (can be fake, just for practice purposes)
- Whatever else you want

[See cool footers <- this is a link 👍 ](https://www.awwwards.com/15-excellent-creative-website-footers.html)

**Comment by designesse** [comment]
Got it :)
