### ISSUE TITLE
Fix remaining linter errors (all client side)

### ISSUE THREAD

**Issue by jenniferwiner** [boulderReactCodingNight/03-react-twitter#56]
We can discuss if any linter rules need to be deactivated. Warnings are OK.

Will require props validation (see MessagesList.jsx for example)

![screen shot 2018-10-18 at 10 59 38 pm](https://user-images.githubusercontent.com/22737121/47198474-a333c900-d329-11e8-9b2e-c933efe045a3.png)

**Comment by colehart** [comment]
I got this.

**Comment by jenniferwiner** [comment]
This has been merged 🎉
