### ISSUE TITLE
Hide messages on splash page when no user is logged in

### ISSUE THREAD

**Issue by jenniferwiner** [boulderReactCodingNight/03-react-twitter#84]
![screen shot 2019-02-19 at 9 09 11 pm](https://user-images.githubusercontent.com/22737121/53065867-b4811380-348a-11e9-8b03-165f384e475c.png)

**Comment by jenniferwiner** [comment]
This is the current look of the app when no user is logged in.

**Comment by airum82** [comment]
We're going to work on this issue
